[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false

[theme]
primaryColor = "#2B70B8"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
